version: '3.8'

services:
  graphqllab-sit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphqllab-sit
    restart: unless-stopped
    ports:
    - "8080:8080"
    environment:
      APP_ENV: sit
    depends_on:
      mysql:
        condition: service_healthy
    networks:
    - set-network-01

  graphqllab-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphqllab-dev
    restart: unless-stopped
    ports:
    - "8080:8080"
    environment:
      APP_ENV: development
    networks:
    - set-network-01

networks:
  set-network-01:
    driver: bridge
